### ISSUE TITLE
RaidReloader: Doesn't work/what does it do?

### ISSUE THREAD

**Issue by Matsyir** [Trevor159/runelite-external-plugins#1]
There isn't much documentation about the plugin so maybe I misunderstand what it's supposed to do, but when I click the Reload Raid button it doesn't do anything, it just appears to dc me for 0.5sec and the layout does not change. If it works as intended I'd like to know what it does.

**Comment by Trevor159** [comment]
It is working as intended. If you look at your instance map it will reload the raid with you at the center. Right now it does not update the raid scouter but you can scout yourself. I have a PR to the main client that would update the scouter when new areas are loaded but that needs to be reviewed there. 

This is said PR https://github.com/runelite/runelite/pull/7981 

Not much I can do to get it reviewed faster but you can comment on it expressing want if you want.

**Comment by Matsyir** [comment]
Oh I see, interesting! Will try it out. Me and my friend assumed it would reset the layout while in lobby without leaving the raid. Admiteddly, that would be pretty OP but I was curious to see if that was the case. I appreciate the quick reply.

**Comment by Trevor159** [comment]
ya, all it does it let you load more of the raid to scout more.
