### ISSUE TITLE
Suggestion: Custom notification sound

### ISSUE THREAD

**Issue by voetre** [Trevor159/runelite-external-plugins#16]
Hey Man,

First off thanks so much for putting this in the plugin hub! It means a lot to have an alternative to the windows tray notifications!

One feature I've always wanted is the option to use a different sound effect for the notifications instead of the windows system alert, would this be possible to implement at some stage?

Thanks for you work on this plugin! 😊

P.s. Sorry for misusing the issues page for suggestions!

**Comment by ShaunDreclin** [comment]
This is already possible! You can change the notification sound to `CUSTOM` in the `RuneLite` config, then add a file called `notification.wav` to `%userprofile%\.runelite` if you want to use a different custom sound.
