### ISSUE TITLE
Stops working

### ISSUE THREAD

**Issue by xCrimin4L** [Trevor159/runelite-external-plugins#2]
When you are using this plugin, and close Runelite then reopen it; The plugin is no longer working and you have to turn it off and back on for it to work.

I also didnt even close runelite and also noticed it mustve stopped working, so I disabled and then enabled it again and it worked. Maybe figure out why it is crashing and fix it? Maybe check what/where an exception is getting thrown.

Chatbox opacity/transparency

**Comment by Trevor159** [comment]
Can you specify which plugin you are talking about?

**Comment by Trevor159** [comment]
closing this as I need more info

**Comment by xCrimin4L** [comment]
For the chatbox opacity, it sometimes just stops working, and you have to turn off and back on the plugin for it to work again. sorry for late reply never saw the first response

**Comment by Trevor159** [comment]
I changed the way the plugin works, I will consider this fixed until I hear otherwise.
