### ISSUE TITLE
RL Tray Notifications is incompatible and requires its author to update it.

### ISSUE THREAD

**Issue by zeroquinc** [Trevor159/runelite-external-plugins#37]
Plugin is incompatible for the last few days. Could this be fixed?

**Comment by Trevor159** [comment]
which plugin?

**Comment by zeroquinc** [comment]
> which plugin?

Sorry, I thought this was a repo for only the RL Tray Notifications plugin, my bad.

**Comment by Trevor159** [comment]
I will try to look into it tmrw, feel free to comment here to remind me in a few days if I never get to it

**Comment by zeroquinc** [comment]
> I will try to look into it tmrw, feel free to comment here to remind me in a few days if I never get to it

Cheers!

**Comment by jaredvanvels** [comment]
> I will try to look into it tmrw, feel free to comment here to remind me in a few days if I never get to it

i also would love to see this fixed we appreciate you

**Comment by Trevor159** [comment]
should be good now, sorry for the wait

**Comment by Hannah-GBS** [comment]
it broked again

**Comment by zeroquinc** [comment]
> it broked again

Works fine here

EDIT: nvm restarted client and its incompatible now

**Comment by Hannah-GBS** [comment]
> > it broked again
> 
> Works fine here

on 1.10.21 it does not 
![image](https://github.com/Trevor159/runelite-external-plugins/assets/7504779/d63c20f2-5eee-42d5-871e-7553a2d4f00e)

**Comment by zeroquinc** [comment]
@Hannah-GBS yeah see my edit I didnt realize my client was open for 10+ hours already so after a restart mine also shows incompatible

**Comment by Hannah-GBS** [comment]
Yeah I thought that might be what happened.

Trevor if you see this before checking the hub, `ClientUI.ICON` used [here](https://github.com/Trevor159/runelite-external-plugins/blob/1d19ab9b23a3dff7f4a89f48c3671091f3614db6/src/main/java/com/trevor/traynotifications/CustomNotification.java#L66) has been deprecated by this commit: 

https://github.com/runelite/runelite/commit/0d2170e696c7a95dd41ea1cbc197422671e5acfa

**Comment by Trevor159** [comment]
fixed again, thanks @Hannah-GBS
