### ISSUE TITLE
Green Screen Runelite Plugin Not Compatible 

### ISSUE THREAD

**Issue by Ch-ncey** [Trevor159/runelite-external-plugins#39]
![green screen](https://github.com/Trevor159/runelite-external-plugins/assets/171523666/b48a263c-153c-4127-bdd2-c9a6a2f15445)

Runelite seems to have updated and the plugin no longer works. Could this please be updated?

There also was a bug with it where you could see through the player character at certain angles.

**Comment by TV-cmd** [comment]
@Trevor159

**Comment by Trevor159** [comment]
thanks for raising this, it should be fixed now
