### ISSUE TITLE
not an issue more of a request

### ISSUE THREAD

**Issue by Makendu-OSRS** [Trevor159/runelite-external-plugins#6]
So your plugin has a lot of deadspace compared to the built in one from jagex. Any chance of making yours more dynamic like theirs where it changes with more points/longe rname?

**Comment by Trevor159** [comment]
I can look into it

**Comment by Makendu-OSRS** [comment]
thanks

**Comment by Trevor159** [comment]
Next runelite update will let you resize any update you want, this should let you resize my overlay.

**Comment by Makendu-OSRS** [comment]
didnt let me resize

**Comment by Trevor159** [comment]
I had to update it to allow it, whenever the update gets merged it will work.

**Comment by Trevor159** [comment]
it is merged
