### ISSUE TITLE
Request (RL Tray Notifications): Select what monitor should be displayed at

### ISSUE THREAD

**Issue by Mimung** [Trevor159/runelite-external-plugins#7]
First off, I love the plugin, the native windows notification was just awful as it would block off a big chunk of the bottom left corner of the monitor.

But would it be possible to make it so that you can configure what monitor that displays the notification ?

**Current behaviour:** The notification will be displayed on the same monitor where the Runelite client is located.

**Comment by Trevor159** [comment]
I can look into this but the main problem I see with this is that we do not have an intuitive way of selecting a monitor in our config. I might be able to have a good config option for "Main Display" and "Current Display", would that work for you?

**Comment by Mimung** [comment]
That sounds like a much better option

**Comment by Trevor159** [comment]
added in https://github.com/Trevor159/runelite-external-plugins/commit/a2d54a6cffe627cd69c04c39988967b1edb3b236

You can restart your client to get the latest update

**Comment by Mimung** [comment]
Works like a charm, thanks
