### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by jacobsuul** [Trevor159/runelite-external-plugins#8]
IDK if its fine to put this here, but I use this Green Screen plugin ALL the time, especially for my stream.

Would it be possible to implement a hotkey to turn it on and off? 
Even more amazing if integrated with streamdeck.

Also, would it be possible to be able to draw NPCs or Objects that are Tagged to draw through green screen?

Is it possible to do like a "Source Output"? and open another mini client that has just the green screen on it, but you can play normal on your regular client?

**Comment by Trevor159** [comment]
A lot late but I added the hotkey, I will probably not add the rest.
